/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Trash.h
 #	source generated by 4D Plugin Wizard
 #	Project : Trash
 #	author : miyako
 #	2020/03/13
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_TRASH_H
#define PLUGIN_TRASH_H

#include "4DPluginAPI.h"
#include "4DPlugin-JSON.h"

#include "C_TEXT.h"

#if VERSIONWIN
#include <process.h>
#include <Rpc.h>
#endif

#pragma mark -

void Trash_item(PA_PluginParameters params);

typedef enum {
    trash_operation_synchronous = 0,
    trash_operation_asynchronous = 1
}trash_operation_mode_t;

#endif /* PLUGIN_TRASH_H */
